### ISSUE TITLE
Reduce command tree

### ISSUE THREAD

**Issue by masmc05** [SirBlobman/BlueSlimeCore#63]
**What version of Spigot are you currently using?**
You can do `/bukkit:version` to find out
1.19.3 purpur
**What version of SirBlobmanCore are you using?**
You can do `/about SirBlobmanCore` to find out
2.6.1.238
**What is your feature request?**
Don't show commands to players that can't use them

This would really to reduce command load time for player from geyser

**Comment by SirBlobman** [comment]
@masmc05 Which commands are you referencing?

**Comment by RedstonedLife** [comment]
@masmc05 Could you elaborate further?

**Comment by masmc05** [comment]
we don't use this plugin anymore, but there was a command with item and nbt, don't remember exactly

**Comment by masmc05** [comment]
closing this since not needed anymore
